global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'lhrinou@gmail.com'
  smtp_auth_username: 'lhrino@gmail.com'
  smtp_auth_password: ''   # Gmail App Password (not your main password!)
  smtp_require_tls: true
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-and-slack'

receivers:
  - name: 'email-and-slack'
    email_configs:
      - to: 'lhrinourd@gmail.com'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/T0JP78H0/B09MS9GC/YyYUCR1S7oh2b3Gr'
        channel: '#alerts'
        send_resolved: true
        title: 'ðŸ”¥ Alert: {{ .CommonLabels.alertname }}'
        text: >
          *Description:* {{ .CommonAnnotations.description }}
          *Instance:* {{ .CommonLabels.instance }}
          *Severity:* {{ .CommonLabels.severity }}

# (Optional) customize alert routing if you want to send critical alerts only to both email and Slack